name: trotters_flutter_app
description: Trotter's is a RoadTrip application. Its app is develop with others school (My digital school) members.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_crashlytics: ^1.0.0
  firebase_core: ^1.0.2
  firebase_analytics: ^7.1.1
  spincircle_bottom_bar: ^1.0.0
  intl: ^0.17.0
  flutter_native_splash: ^1.2.3
  custom_refresh_indicator: ^1.0.0
  modal_bottom_sheet: ^2.0.0
  image_picker: ^0.8.4+2
  http: ^0.13.4
  google_maps_flutter: ^2.0.11
  carousel_slider: ^4.0.0
  container_tab_indicator: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/trotterslogo.png
    - assets/trotterslogowhite.png
    - assets/cup.png
    - assets/cup2.png
    - assets/ice1.png
    - assets/ice2.png
    - assets/ice3.png
    - assets/mint.png
    - assets/spoon.png
    - assets/arrow.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg



  fonts:

    - family: icomoon
      fonts:
      - asset: fonts/icomoon.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/trotterslogo.png"


